### ISSUE TITLE
Windows - 'flow' could not be spawned

### ISSUE THREAD

**Issue by SC7639** [nmn/autocomplete-flow#3]
I've put flow in the my path so in cmd if I type flow it runs flow and I've tried using the absolute path to flow but I am still getting  the message.

```
'flow' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```

I'm using the latest Flowtype binary for Windows which can be found at http://www.ocamlpro.com/pub/ocpwin/flow-builds/

OS: Windows 10

**Comment by nmn** [comment]
This is probably a problem specific to windows. I don't have a windows machine to test with but I'll check for any *Nix specific code in there and try to fix the problem.

BTW, can you also check the console and give me any extra information you may find. It might help me find the problem.

**Comment by nmn** [comment]
Can you tell me what exactly is the value you've set for the the flow path in the config.
Also, if you use that path in the cmdline to try to use flow, does it work?

I don't have any *nix specific code, so I think with your help I can fix this. I don't have a windows machine to test on myself.

**Comment by nmn** [comment]
I had similar errors on Mac in a new version. Can you check if the newest version works for you?

PS: try setting the absolute path again, of course.
