### ISSUE TITLE
[Autocomplete-Flow] Missing .flowconfig file

### ISSUE THREAD

**Issue by neurosnap** [nmn/autocomplete-flow#5]
I get this notification even when I'm not working on a project that uses flow.  It seems like it should not notify us unless `// @flow` is at the top of the file being used.

**Comment by ewnd9** [comment]
I've removed that warning in my fork https://github.com/ewnd9/autocomplete-flow/commit/4c0d5ff4f7abcd2794a57bb2d6a9072ed5a74660

``` sh
$ apm install ewnd9/autocomplete-flow
```

**Comment by nmn** [comment]
@ewnd9 Mind making a PR?

**Comment by sunjay** [comment]
@nmn Can you just delete the lines that @ewnd9 commented out in his commit? This warning is really annoying. Send it once fine, but over and over again is too much.

**Comment by ewnd9** [comment]
@sunjay PR is already merged https://github.com/nmn/autocomplete-flow/pull/6

**Comment by svagi** [comment]
@nmn When this fix will be released?

**Comment by kaievns** [comment]
release this please! i love the package, but flipping between flow and not flow based projects is a pain
